### ISSUE TITLE
Can't git clone the app

### ISSUE THREAD

**Issue by tkserver** [react-native-elements/react-native-elements-app#53] opened 2018-04-27 20:09 UTC
**When I try to clone this repo:**
it clone --recursive https://github.com/react-native-training/react-native-elements-app.git

**This happens:**
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by xavier-villelegier** [comment] 2018-04-29 10:27
Duplicate of #50

**Closed as completed by xavier-villelegier** 2018-04-29 10:27 UTC
